#ifndef __ACTIVITY3_H__
#define __ACTIVITY3_H__

#include <avr/io.h>

#define OCCUPANCY_PIN PD4/* OCCUPANCY Pin number  */
#define CRO_DISPLAYPIN PD6/* CRO DISPLAY PIN OUTPUT PIN FOR PWM */

#define TIMER_COUNTER_CONTROL_REGISTER1A TCCR1A/* TIMER CONTROL REGISTER A */
#define TIMER_COUNTER_CONTROL_REGISTER1B TCCR1B/* TIMER CONTROL REGISTER B */
#define WAVEGENERATION_MODE0 WGM10/* NON INVERTING MODE FAST PWM */
#define WAVEGENERATION_MODE1 WGM11/* NON INVERTING MODE FAST PWM */
#define NONINVERTING_MODE COM1A1/*  NON INVERTING MODE */
#define OUTPUT_COMPAIR_REGISTERA OCR1A/* OUTPUT COMPAIR REGISTER A */

void InitPWM(void);
uint16_t OutPWM (uint16_t value);

#endif
